language: ruby
rvm:
  - 2.1
script: "bundle exec jekyll build"

branches:
  except:
    - images
    - gh-pages
    - i18n

notifications:
  email: false
  slack:
    rooms: jahirfiquitiva:StCMaxV85iad38DdSMBY43xW
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}: '%{commit_subject}'>)  by %{author} for %{repository_name}@%{branch}, %{result} in %{duration}. <%{build_url}|Check details>."