language: ruby
cache: bundler
sudo: false
dist: trusty

rvm:
  - 2.5

before_install:
  - gem update --system
  - gem install --remote bundler
  - bundle --version

script: "bundle exec jekyll build"

branches:
  except:
    - images
    - i18n

notifications:
  email: false
  slack:
    rooms: jahirfiquitiva:StCMaxV85iad38DdSMBY43xW
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}: '%{commit_subject}'>)  by %{author} for %{repository_name}@%{branch}, %{result} in %{duration}. <%{build_url}|Check details>."